baseURL = "http://russellgao.github.io/blogs"
languageCode = "en"
DefaultContentLanguage = "en"
title = "大大很二的博客"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "大大很二的博客"
author = "russell"
description = "用技术改变世界"
profilePicture = "https://gitee.com/russellgao/blogs-image/raw/master/images/russellgao.png"
keywords = ""
favicon = "https://gitee.com/russellgao/blogs-image/raw/master/images/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
# Google Site Verification
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/russellgao/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:1060745366@qq.com"

## Menu items

[menu]

[[menu.main]]
name = "首页"
identifier = "home"
weight = 100
url = "/"

[[menu.main]]
name = "Kubernetes"
weight = 200
identifier = "kubernetes"
url = "/kubernetes/"

[[menu.main]]
name = "Python"
weight = 200
identifier = "python"
url = "/python/"

[[menu.main]]
name = "Golang"
weight = 200
identifier = "golang"
url = "/golang/"

[[menu.main]]
name = "Devops"
weight = 200
identifier = "devops"
url = "/devops/"

[[menu.main]]
name = "算法"
weight = 200
identifier = "argorithm"
url = "/argorithm/"

[[menu.main]]
name = "关于"
weight = 300
identifier = "about"
url = "/about/"
